name: CI-lowest

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:

  checks:
    name: Psalm
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Setup PHP
          uses: shivammathur/setup-php@master
          with:
            php-version: 7.4
            extensions: mbstring

        - name: Get Composer Cache Directory
          id: composer-cache
          run: echo "::set-output name=dir::$(composer config cache-files-dir)"

        - name: Cache dependencies
          uses: actions/cache@v1
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
            restore-keys: ${{ runner.os }}-composer-

      - run: composer require vimeo/psalm --prefer-lowest && composer require orklah/psalm-strict-visibility --prefer-lowest && vendor/bin/psalm
